// <auto-generated />
using System;
using BeanFiendAPI.Persistence.SQLite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeanFiendAPI.Persistence.Migrations
{
    [DbContext(typeof(BeanFiendSQLiteDbContext))]
    partial class BeanFiendSQLiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("BeanFiendAPI.Model.Beaner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Beaners");
                });

            modelBuilder.Entity("BeanFiendAPI.Model.Coffee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BeanerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCream")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSugar")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeanerId");

                    b.ToTable("Coffees");
                });

            modelBuilder.Entity("BeanFiendAPI.Model.Coffee", b =>
                {
                    b.HasOne("BeanFiendAPI.Model.Beaner", null)
                        .WithMany("Coffees")
                        .HasForeignKey("BeanerId");
                });

            modelBuilder.Entity("BeanFiendAPI.Model.Beaner", b =>
                {
                    b.Navigation("Coffees");
                });
#pragma warning restore 612, 618
        }
    }
}
